---
format:
  commonmark:
    variant: -raw_html+tex_math_dollars
    wrap: none
    mermaid-format: png
crossref:
  fig-prefix: Figure
  tbl-prefix: Table
output: asis
engine: julia
julia: 
  exeflags: ["--project=./"]
execute:
  eval: false
  echo: true
---

# Experiments

This is the folder that contains all code used to generate the results in the paper. You can also use it to reproduce the results. 

## Getting Started

To get started activate the environment in the Julia REPL:

```{julia}
# eval: false

using Pkg; Pkg.activate("paper/experiments")
```

Next, we load the `CTExperiments` package---a helper package that ships some additional functionality relevant only to the experiments run for the paper. 

```{julia}
using CTExperiments
```

## Running Experiments

The Julia functions that live directly under `paper/experiments/` can be used to run the experiments. The main scripts of interest are:

- `run_grid.jl` and `run_grid_sequentially.jl` which can be used to train model architectures on data according to specifications in configuration files (TOML).
- `run_evaluation_grid.jl` and  `run_evaluation_grid_sequentially.jl` which can be used to evaluate previously run experiments.

The `_sequentially` suffix indicates that experiments are run sequentially and tasks underlying experiments are distributed across processes (as opposed to distributed experiments across processes).

### Configurations

To configure and keep track of hyperparameters for differenct experiments, we use TOML files. The configurations used for our various experiments can be found in `paper/experiments/configs/`. The following files are of particular relevance:

- `single.toml`: configures the main experiments that produced the main results without mutability constraints.
- `mutability_*.toml`: configures the main experiments that produced the main results with mutability constraints.

The remaining configuration files include those for extensive grid searches used for hyperparameter tuning.

### Command Line Usage

The Julia scripts introduced above look for certain environment variables pertaining to the configurations of experiments and evaluations, as well as paths to directories that will used to store results. Some of the environment variables specified in a `.env` file. Before running batch jobs, you therefore want to specify these variables as illustrated in the following example:

```
source .env                                           # declares a few environment variables
export CONFIG=paper/experiments/configs/single.toml   # path to configuration file
export OUTPUT_SUBDIR="final_run"                      # path to store outputs (root directory is /paper/experiments/output by default)
```

You can then run scripts directly from the command line like so:

```
julia --project=$EXPERIMENT_DIR $EXPERIMENT_DIR/run_grid.jl --config=$CONFIG --data="lin_sep" --model="mlp"
```

Note that it is possible to provide extra arguments (here `--data` or `--model`) to overwrite specifications in the configuration file. To understand what arguments you can provide, we recommend familiarizing yourself with the code base in `paper/experiments/CTExperiments/`.

### Cluster Jobs

To run jobs on a cluster, you can use any of bash scripts under `paper/experiments/jobs/`. Assuming you have already exported environment variables as discussed above, you can run cluster jobs as follows:

```
sbatch --time=00:30:00 --ntasks=20 --cpus-per-task=$NTHREADS $RUN_GRID_SEQ --model=mlp --tau=0.5 --reg_strength=0.01 --data=lin_sep
```

Here we have specified a run time, `--time`, the number of processes to be used, `--ntasks`, and how many threads to use (defaults to 1). The `$RUN_GRID_SEQ` variable points to `paper/experiments/jobs/run_grid_sequentially.sh`. The remaining variables are supplied as `ARGS` to Julia and can be used to configure the experiment, as already discussed above. 

## Other Things

Some anecdotal or illustrative results were produced in simple Julia scripts or interactive notebooks. In fact, many of the Quarto notebooks (.qmd) in `paper/sections/other/` contain code cells that produce tables and charts. Note that many of these depend on experiment output being available that is not shipped with this repository and therefore first needs to be created. We will release the experiment outputs upon publication in a designated data repository, fit to handle large amounts of data.

### Figure 1

The chart in Figure 1 of the paper is produced in [paper/sections/other/constraints.qmd](../sections/other/constraints.qmd).

### Figure 2

The chart in Figure 2 of the paper can be reproduced using the following script: [paper/experiments/mnist_chart.jl](mnist_chart.jl).

### Figure 3

The chart in Figure 3 of the paper is produced in [paper/sections/other/main_results.qmd](../sections/other/main_results.qmd). Integrated gradients were computed using [paper/experiments/integrated_gradients_mnist.jl](integrated_gradients_mnist.jl)

### Integrated Gradients

The results for integrated gradients presented in the appendix can be reproduced using [paper/experiments/run_integrated_gradients.jl](run_integrated_gradients.jl).
